//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginRegTable
    {
        public int usrid { get; set; }
        public string usrFirstName { get; set; }
        public string usrLastName { get; set; }
        public string usrEmail { get; set; }
        public string usrPasswd { get; set; }
        public Nullable<System.DateTime> usrDOB { get; set; }
        public string usrCity { get; set; }
        public string usrConfPasswd { get; set; }
    }
}
