//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTable
    {
        public int Productid { get; set; }
        public string ProductName { get; set; }
        public int ProductPriceRange { get; set; }
        public int ProductCapacityRange { get; set; }
        public string ProductLocation { get; set; }
        public string ProductAdress { get; set; }
        public string ProductImagePath { get; set; }
        public string ProductImagePath1 { get; set; }
        public string ProductImagePath2 { get; set; }
        public string ProductImagePath3 { get; set; }
        public string ProductImagePath4 { get; set; }
        public string ProductDetails { get; set; }
    }
}
