//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRegistration
    {
        public int srno { get; set; }
        public int usrid { get; set; }
        public int Productid { get; set; }
        public string ProductLocation { get; set; }
        public double ratings { get; set; }
    }
}
